name: AreaProtection
description: AreaProtection
main: net.llamagames.AreaProtection.AreaProtection
version: 2.0.4
api: 1.0.0
author: SchdowNVIDIA
website: llama-games.net
softdepend:
  - MobPlugin